openapi: '3.0.1'
info:
  title: Shortener
  version: '0.2.0'
servers:
  - url: 'http://localhost:8000/'
  - url: 'https://localhost:8000/'
paths:
  /api/account/login:
    post:
      tags:
        - login
      description: 登录接口
      operationId: login
      requestBody:
        description: 登录系统
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginParams'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResult'
        '401':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: body
    x-swagger-router-controller: api
  /api/account/logout:
    post:
      description: 退出登录接口
      operationId: logout
      tags:
        - login
      responses:
        '204':
          description: Success
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    x-swagger-router-controller: api
  /api/users/current:
    get:
      tags:
        - api
      description: 获取当前的用户
      operationId: currentUser
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUser'
        '401':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    x-swagger-router-controller: api

  /api/shortens:
    post:
      tags:
        - shorten
      summary: '添加短网址'
      description: '添加一个新的短网址'
      operationId: 'addShorten'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Shorten'
      responses:
        '201':
          description: '短网址创建成功'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortenResponse'
        '400':
          description: '请求错误'
        '409':
          description: '短网址已存在'
        '500':
          description: '操作失败'
        default:
          description: '未知错误'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    get:
      tags:
        - shorten
      summary: '获取所有短址信息'
      description: '获取所有短址信息'
      operationId: 'getShortens'
      parameters:
        - name: page
          in: query
          description: '页码'
          required: false
          schema:
            type: integer
            default: 1
        - name: page_size
          in: query
          description: '每页条数'
          required: false
          schema:
            type: integer
            default: 10
        - name: sort_by
          in: query
          description: '排序字段'
          required: false
          schema:
            type: string
            default: 'created_time'
            enum:
              - created_time
              - updated_time
        - name: order
          in: query
          description: '排序方向'
          required: false
          schema:
            type: string
            default: 'desc'
            enum:
              - asc
              - desc
        - name: status
          in: query
          description: '状态'
          required: false
          schema:
            type: integer
            default: 0
            enum:
              - 0
              - 1
              - 2
      responses:
        '200':
          description: '操作成功'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShortenResponse'
        default:
          description: '未知错误'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/shorten/{code}:
    get:
      tags:
        - shorten
      summary: '获取短网址信息'
      description: '通过短码获取短网址信息'
      operationId: 'getShorten'
      parameters:
        - name: code
          in: path
          description: '短码'
          required: true
          schema:
            type: string
            maxLength: 16
            pattern: '^[a-zA-Z0-9]+$'
            example: 'aBc123'
      responses:
        '200':
          description: '操作成功'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortenResponse'
        '400':
          description: '请求错误'
        '404':
          description: '短网址不存在'
        '500':
          description: '操作失败'
        default:
          description: '未知错误'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      tags:
        - shorten
      summary: '更新短网址'
      description: '更新一个短网址'
      operationId: 'updateShorten'
      parameters:
        - name: code
          in: path
          description: '短码'
          required: true
          schema:
            type: string
            maxLength: 16
            pattern: '^[a-zA-Z0-9]+$'
            example: 'aBc123'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortenUpdate'
      responses:
        '200':
          description: '操作成功'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortenResponse'
        '400':
          description: '请求错误'
        '404':
          description: '短码不存在'
        '500':
          description: '操作失败'
        default:
          description: '未知错误'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      tags:
        - shorten
      summary: '删除短网址'
      description: '删除一个短网址'
      operationId: 'deleteShorten'
      parameters:
        - name: code
          in: path
          description: '短码'
          required: true
          schema:
            type: string
            maxLength: 8
            pattern: '^[a-zA-Z0-9]+$'
            example: 'aBc123'
      responses:
        '204':
          description: '操作成功'
        '400':
          description: '请求错误'
        '404':
          description: '短网址不存在'
        '500':
          description: '操作失败'
        default:
          description: '未知错误'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    LoginParams:
      type: object
      properties:
        username:
          description: 用户名
          type: string
        password:
          description: 密码
          type: string
        auto:
          description: 是否自动登录
          type: boolean
    LoginResult:
      type: object
      properties:
        token:
          type: string
          description: 登录成功后返回的 token
    CurrentUser:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: 用户ID
        name:
          type: string
          description: 用户名
        level:
          type: integer
          format: int32
          enum: [1, 2]
          description: 等级，只能是1或2
    ErrorResponse:
      required:
        - errorCode
      type: object
      properties:
        errorCode:
          type: string
          description: 业务约定的错误码
        errorMessage:
          type: string
          description: 业务上的错误信息
        success:
          type: boolean
          description: 业务上的请求是否成功

    Shorten:
      type: object
      properties:
        original_url:
          type: string
          format: uri
          description: '原始长网址'
        code:
          type: string
          description: '短码'
          maxLength: 16
          pattern: '^[a-zA-Z0-9]+$'
        describe:
          type: string
          description: '长网址描述'
      required:
        - original_url
        - code

    ShortenUpdate:
      type: object
      properties:
        original_url:
          type: string
          format: uri
          description: '原始长网址'
        describe:
          type: string
          description: '长网址描述'
      required:
        - original_url

    ShortenResponse:
      type: object
      properties:
        id:
          type: integer
          description: 'ID'
        code:
          type: string
          description: '短码'
          maxLength: 16
          pattern: '^[a-zA-Z0-9]+$'
        short_url:
          type: string
          format: uri
          description: '短网址'
        original_url:
          type: string
          format: uri
          description: '原始长网址'
        describe:
          type: string
          description: '长网址描述'
        status:
          type: integer
          description: '状态'
        created_time:
          type: string
          description: '创建时间'
        updated_time:
          type: string
          description: '更新时间'

    Error:
      type: object
      properties:
        errcode:
          type: integer
          description: '错误代码'
        errinfo:
          type: string
          description: '错误信息'
